<?php

declare(strict_types=1);

namespace App\Tests\PhpStan;

/** The files #1171 has yet to sweep, grouped by the PR that sweeps them; each PR deletes its own group. */
final class UnsweptCommentFiles
{
    public const array FILES = [
        // U
        'src/Controller/Api/ReadingActivityController.php',
        'src/Controller/Api/RecommendationRunHistoryController.php',
        'src/Controller/Api/RecommendationSettingsController.php',
        'src/Dto/Recommendation/SaveRecommendationSettingsRequest.php',
        'src/Entity/RecommendationSettings.php',
        'src/Enum/SupportedLocale.php',
        'src/Http/RecommendationSettingsJson.php',
        'src/Repository/RecommendationItemRepository.php',
        'src/Repository/RecommendationRunHistoryRepository.php',
        'src/Repository/RecommendationRunLogRepository.php',
        'src/Repository/RecommendationRunRepository.php',
        'src/Repository/RecommendationRunTimingRepository.php',
        'src/Service/Clock/Model/ViewerTimeZoneModel.php',
        'src/Service/Clock/NaiveUtcClock.php',
        'src/Service/Recommendation/Exception/RecommendationRunCancelledException.php',
        'src/Service/Recommendation/Exception/RecommendationTickLockLostException.php',
        'src/Service/Recommendation/Exception/UnknownHistoryMonthException.php',
        'src/Service/Recommendation/Feed/HistoryMonthSummariser.php',
        'src/Service/Recommendation/Feed/Model/FeedAnnotationVisibilityModel.php',
        'src/Service/Recommendation/Feed/Model/HistoryMonthModel.php',
        'src/Service/Recommendation/Feed/Model/MonthWindowModel.php',
        'src/Service/Recommendation/Feed/Model/RecommendationForYouSummaryModel.php',
        'src/Service/Recommendation/Feed/RecommendationDebugLogLoader.php',
        'src/Service/Recommendation/Feed/RecommendationRunHistory.php',
        'src/Service/Recommendation/Prompt/Model/CandidatePoolRequestModel.php',
        'src/Service/Recommendation/Prompt/Model/CandidatePoolSummaryModel.php',
        'src/Service/Recommendation/Prompt/Model/ConsolidationParseResultModel.php',
        'src/Service/Recommendation/Prompt/Model/ProfileParseResultModel.php',
        'src/Service/Recommendation/Prompt/Model/RecommendationHistoryModel.php',
        'src/Service/Recommendation/Prompt/Model/RecommendationPickModel.php',
        'src/Service/Recommendation/Prompt/Model/RecommendationResponseSchema.php',
        'src/Service/Recommendation/Prompt/ModelReplyJsonDecoder.php',
        'src/Service/Recommendation/Prompt/PlausibleDuplicateShare.php',
        'src/Service/Recommendation/Prompt/RecommendationAnswerBudget.php',
        'src/Service/Recommendation/Prompt/RecommendationConsolidationParser.php',
        'src/Service/Recommendation/Prompt/RecommendationPickParser.php',
        'src/Service/Recommendation/Prompt/RecommendationPickSalvager.php',
        'src/Service/Recommendation/Prompt/RecommendationProfileParser.php',
        'src/Service/Recommendation/Prompt/RecommendationPromptBuilder.php',
        'src/Service/Recommendation/Prompt/Support/RecommendationPromptText.php',
        'src/Service/Recommendation/Settings/Model/EffectiveRecommendationSettingsModel.php',
        'src/Service/Recommendation/Settings/Model/RecommendationPackingSettingsModel.php',
        'src/Service/Recommendation/Settings/RecommendationSettingsResolver.php',
        'src/Service/Recommendation/Settings/RecommendationSettingsWriter.php',
        // V
        'tests/Controller/Api/RecommendationRunControllerTest.php',
        'tests/Controller/Api/RecommendationRunHistoryControllerTest.php',
        'tests/Controller/Api/RecommendationSettingsControllerTest.php',
        'tests/Repository/RecommendationItemRepositoryTest.php',
        'tests/Repository/RecommendationRunHistoryRepositoryTest.php',
        'tests/Repository/RecommendationRunRepositoryTest.php',
        'tests/Service/Recommendation/Feed/Model/MonthWindowModelTest.php',
        'tests/Service/Recommendation/Feed/RecommendationForYouSummaryProviderTest.php',
        'tests/Service/Recommendation/Prompt/Factory/RecommendationCompletionRequestFactoryTest.php',
        'tests/Service/Recommendation/Prompt/RecommendationAnswerBudgetTest.php',
        'tests/Service/Recommendation/Prompt/RecommendationCandidateLoaderTest.php',
        'tests/Service/Recommendation/Prompt/RecommendationConsolidationParserTest.php',
        'tests/Service/Recommendation/Prompt/RecommendationPickParserTest.php',
        'tests/Service/Recommendation/Prompt/RecommendationPromptBuilderTest.php',
        'tests/Service/Recommendation/Run/DueRecommendationRunFinderTest.php',
        'tests/Service/Recommendation/Run/ForYouSweepTest.php',
        'tests/Service/Recommendation/Run/Pass/RecordedCallTest.php',
        'tests/Service/Recommendation/Run/RecommendationCallRecorderTest.php',
        'tests/Service/Recommendation/Run/RecommendationConsolidationResolverTest.php',
        'tests/Service/Recommendation/Run/RecommendationDrainSpawnerTest.php',
        'tests/Service/Recommendation/Run/RecommendationPipelineTest.php',
        'tests/Service/Recommendation/Run/RecommendationProfileDistillerTest.php',
        'tests/Service/Recommendation/Run/RecommendationRunAdvancerTest.php',
        'tests/Service/Recommendation/Run/RecommendationRunPurgerTest.php',
        'tests/Service/Recommendation/Run/RecommendationRunStarterTest.php',
        'tests/Service/Recommendation/Run/SweepStreamHeartbeatTest.php',
        'tests/Service/Recommendation/Run/TickLockKeepaliveTest.php',
        'tests/Service/Recommendation/Run/WorkerPresenceTest.php',
        'tests/Service/Recommendation/Settings/RecommendationSettingsWriterTest.php',
    ];
}
