<?php

declare(strict_types=1);

namespace App\Tests\Service\Backup;

use App\Entity\ActionToken;
use App\Entity\AiProviderSettings;
use App\Entity\CatalogCategory;
use App\Entity\CatalogFeed;
use App\Entity\Entry;
use App\Entity\EntryState;
use App\Entity\Feed;
use App\Entity\InstanceSetting;
use App\Entity\Preferences;
use App\Entity\ProxyServerSettings;
use App\Entity\RecommendationItem;
use App\Entity\RecommendationRun;
use App\Entity\RecommendationRunLog;
use App\Entity\RecommendationSettings;
use App\Entity\SavedSearch;
use App\Entity\Subscription;
use App\Entity\SubscriptionTag;
use App\Entity\Tag;
use App\Entity\User;
use App\Entity\UserIdentity;
use App\Entity\WorkerHeartbeat;
use App\Service\Backup\AccountBackupExporter;
use App\Service\Backup\BackupSchema;
use App\Tests\DbTestCase;
use App\Tests\Support\BackupFieldDeclarations;
use App\Tests\Support\FullyPopulatedAccount;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

/**
 * Couples the backup format to the ORM schema, which nothing else does.
 *
 * The backup is a hand-maintained projection: an exporter that writes named
 * JSON keys, and line DTOs that read them. A column added to a backed-up
 * table reaches neither unless a person remembers. Three schema changes
 * landed on backed-up tables in the six days after the format shipped and two
 * of them were missed, silently, because a nullable column accepts an INSERT
 * that never names it (#556).
 *
 * The guard is deliberately narrow in one way: it reads the ORM mapping, so a
 * migration that adds a column with no entity mapping is invisible to it.
 * Everything in this tree is attribute-mapped, and an unmapped column holds no
 * user data by construction.
 */
final class BackupSchemaCoverageTest extends DbTestCase
{
    /**
     * Every entity's surrogate key. A backup is identity-free by design — the
     * restore assigns new ids — so listing `id` nine times would be noise.
     */
    private const array UNIVERSALLY_SKIPPED = ['id'];

    /**
     * A restore writes into the account that is signed in, so no line names an
     * owner. It could not: an owner in the file would be an owner the user
     * picked.
     */
    private const string OWNER_IS_THE_RESTORING_ACCOUNT = 'The owning account. A restore writes into '
        . 'the signed-in account, so no line names an owner — an owner read from the file would be '
        . 'one the user chose for themselves.';

    /** The line discriminator, written on every kind and naming no field. */
    private const array EVERY_LINE = ['kind'];

    /**
     * The header and footer describe the file rather than any entity, so no
     * declaration claims their keys and they are enumerated here instead.
     *
     * Kept per kind rather than excused everywhere: the header's own
     * `createdAt` must not license a `createdAt` appearing on some other line.
     */
    private const array FILE_SCAFFOLDING = [
        BackupSchema::KIND_HEADER => ['schemaVersion', 'createdAt', 'sourceUrl', 'sourceEmail'],
        BackupSchema::KIND_FOOTER => [
            'counts', 'counts.tag', 'counts.savedSearch', 'counts.feed', 'counts.subscription',
            'counts.entry', 'counts.entryState',
        ],
    ];

    /**
     * Rows that belong to the instance, not to any one account. A field added
     * to one of these cannot produce the failure this test guards against,
     * because no per-account projection of them exists.
     */
    private const array INSTANCE_SCOPED = [
        InstanceSetting::class => 'Instance-wide configuration, identical for every account.',
        ProxyServerSettings::class => 'The instance\'s egress configuration (#490); an operator setting.',
        CatalogCategory::class => 'The shared discovery catalog, seeded per instance.',
        CatalogFeed::class => 'The shared discovery catalog, seeded per instance.',
        WorkerHeartbeat::class => 'Liveness telemetry for the refresh worker.',
    ];

    /**
     * Account-scoped and dropped in full. Declared per entity rather than per
     * field: see the plan's stated deviation.
     * testTheExportWritesNoKeyThatNoDeclarationClaims() is what keeps that
     * shorthand honest — these six have no field-by-field declaration, so the
     * only way one of them starting to be exported becomes visible is the
     * insistence that every key on every line is claimed by something.
     */
    private const array ACCOUNT_SCOPED_WHOLLY_DROPPED = [
        AiProviderSettings::class => 'Model endpoints and API keys. A backup is a file the '
            . 'user handles and mails around; credentials do not belong in one.',
        UserIdentity::class => 'OAuth identity links — see NEVER_BACKED_UP\'s reasoning.',
        ActionToken::class => 'Short-lived, single-use verification and reset tokens.',
        RecommendationRun::class => 'Run history. Regenerated by running the engine; large, and '
            . 'meaningless once its entries are gone.',
        RecommendationRunLog::class => 'Per-run diagnostics, tied to a run that is not restored.',
        RecommendationItem::class => 'Per-run picks, tied to a run that is not restored.',
    ];

    /**
     * Doctrine class => [field or association => exported JSON key, or the
     * list of keys when one field is written as several — an entry reference
     * is a feed URL and a GUID hash together, and neither half identifies an
     * entry on its own].
     *
     * Lives in `BackupFieldDeclarations::BACKED_UP` (test/Support), not here,
     * because `AccountRestorerTest` drives its own round-trip coverage off
     * the identical list — this class's own write-direction proof would mean
     * nothing if the read-direction test could silently fall out of step
     * with it (#556).
     */
    private const array BACKED_UP = BackupFieldDeclarations::BACKED_UP;

    /** Doctrine class => [field => why a backup leaves it behind]. */
    private const array NOT_BACKED_UP = [
        User::class => [
            'status' => 'The account\'s moderation state, decided by the sign-up flow and the '
                . 'admin. A restore runs against an account that is already active.',
            'createdAt' => 'When this instance opened the account. A restore fills an account that '
                . 'already exists rather than creating one, so the account\'s own age is not the '
                . 'file\'s to set.',
            'approvedAt' => 'An admin\'s decision on this instance, not the reader\'s data.',
            'lastLoginAt' => 'Sign-in telemetry, rewritten by the token issuer on the very next '
                . 'login. Restoring it would be stale before the user saw it.',
            'trialEndsAt' => 'The instance\'s terms for this account, granted by the sign-up flow '
                . 'or by an admin.',
            'maxSubscriptions' => 'A per-account cap an admin grants. Carried in the file, it '
                . 'would be a quota the account holder writes for themselves.',
            'preferences' => 'Not a carried value: the pointer to the account\'s preferences row. '
                . 'The account line inlines that row\'s field instead of nesting it, so the '
                . 'pointer itself becomes no key.',
            'activeAiProviderSettings' => 'Points at an AiProviderSettings row, which '
                . 'ACCOUNT_SCOPED_WHOLLY_DROPPED leaves out in full.',
        ],
        Preferences::class => [
            'user' => self::OWNER_IS_THE_RESTORING_ACCOUNT,
        ],
        RecommendationSettings::class => [
            'user' => self::OWNER_IS_THE_RESTORING_ACCOUNT,
        ],
        Tag::class => [
            'user' => self::OWNER_IS_THE_RESTORING_ACCOUNT,
        ],
        SavedSearch::class => [
            'user' => self::OWNER_IS_THE_RESTORING_ACCOUNT,
        ],
        Feed::class => [
            'status' => 'Live fetch state, not the user\'s data. A restored feed starts clean.',
            'etag' => 'The HTTP validator for the last body this instance fetched. A restore has '
                . 'no such body, and a carried-over validator would make the first refresh take a '
                . '304 over an empty feed.',
            'lastModified' => 'The Last-Modified half of the same conditional-request pair as '
                . 'etag, dropped for the same reason.',
            'fetchSchedule.lastFetchedAt' => 'Fetch bookkeeping owned by FeedScheduler. A restored '
                . 'feed has never been fetched by this instance.',
            'fetchSchedule.lastSuccessfulFetchAt' => 'The same bookkeeping. Carried over, it would '
                . 'report a feed as healthy before this instance had reached it once.',
            'fetchSchedule.nextFetchAt' => 'The scheduler\'s due stamp. Left unset so the restored '
                . 'feed is due at once, which is what a reader wants after a restore.',
            'fetchSchedule.fetchIntervalMinutes' => 'A restored feed gets a virgin schedule and is '
                . 'refreshed immediately by the client — same rule as the OPML import.',
            'fetchSchedule.consecutiveFailures' => 'A failure streak against one instance\'s '
                . 'network. Restoring it would apply another host\'s backoff to a feed this one '
                . 'has never tried.',
            'fetchSchedule.lastErrorMessage' => 'The message behind that streak, and meaningless '
                . 'once the streak itself is not carried.',
        ],
        Subscription::class => [
            'user' => self::OWNER_IS_THE_RESTORING_ACCOUNT,
        ],
        SubscriptionTag::class => [
            'subscription' => 'The back-pointer to the parent line. Every subscription line nests '
                . 'its own tag references, so a join row never has to name the subscription it '
                . 'sits under.',
        ],
        Entry::class => [
            'urlHash' => 'Derived: sha256 of UrlNormalizer::normalize(url), which the file '
                . 'already carries. EntryBatchInserter recomputes it on restore, so it is '
                . 'never stale and never has to be dropped from the format later.',
        ],
        EntryState::class => [
            'user' => self::OWNER_IS_THE_RESTORING_ACCOUNT,
        ],
    ];

    /**
     * Security boundaries, not product decisions. Moving a field out of this
     * list is never a fix for a red test.
     *
     * `roles` is the sharp one: a restore writes what the file says, and a
     * backup is a file the user supplies. If roles were restorable, any
     * account holder could hand-edit one line and grant themselves
     * ROLE_ADMIN. Restorable identity links would let a user attach someone
     * else's OAuth identity to their own account, and a restorable email
     * would let them move onto an address they do not control.
     *
     * `passwordChangedAt` is here for the same class of reason rather than as
     * a product choice: it is the token-revocation control itself, and a user
     * who can write it can undo a revocation.
     */
    private const array NEVER_BACKED_UP = [
        User::class => [
            'roles' => 'Privilege escalation: a hand-edited backup would grant ROLE_ADMIN.',
            'email' => 'Account identity; a restore must never move an account to another address.',
            'passwordHash' => 'Credential material.',
            'passwordChangedAt' => 'Token revocation. PasswordChangeTokenInvalidator rejects any '
                . 'JWT whose `iat` is older than this stamp, which is the whole mechanism by '
                . 'which a password reset kills tokens already in an attacker\'s hands. A '
                . 'restorable — or nullable — stamp would let the account holder roll it back '
                . 'from a file they wrote and bring a revoked bearer token back to life, which '
                . 'is the exact attack the column was added to close.',
        ],
    ];

    /**
     * Doctrine class => the `kind` of the line its fields are written on.
     *
     * Lives in `BackupFieldDeclarations::KIND_OF` for the same reason
     * `BACKED_UP` above does.
     */
    private const array KIND_OF = BackupFieldDeclarations::KIND_OF;

    /**
     * The headings the user-facing tables live under. A dropped thing is
     * looked for under its own heading and nowhere else.
     */
    private const string SECTION_INSTANCE_SCOPED = '### 6.1';
    private const string SECTION_WHOLLY_DROPPED = '### 6.2';
    private const string SECTION_DROPPED_FIELDS = '### 6.3';
    private const string SECTION_NEVER_WRITTEN = '## 7.';

    public function testEveryPersistedFieldOfACoveredEntityCarriesADecision(): void
    {
        foreach (array_keys(self::BACKED_UP) as $entityClass) {
            foreach ($this->persistedNames($entityClass) as $name) {
                self::assertTrue(
                    $this->isDeclared($entityClass, $name),
                    sprintf(
                        "%s::$%s is persisted but no backup decision exists for it.\n"
                        . 'Add it to BACKED_UP, NOT_BACKED_UP or NEVER_BACKED_UP in %s, '
                        . 'and add a row to docs/backup.md.',
                        $entityClass,
                        $name,
                        self::class,
                    ),
                );
            }
        }
    }

    /**
     * The per-field lists above only cover entities BACKED_UP names. A new
     * entity would slip past them entirely, so its scope is decided here.
     */
    public function testEveryMappedEntityCarriesAScopeDecision(): void
    {
        foreach ($this->mappedEntityClasses() as $entityClass) {
            self::assertTrue(
                $this->hasScopeDecision($entityClass),
                sprintf(
                    "%s is mapped but no backup scope decision exists for it.\n"
                    . 'Add it to BACKED_UP, INSTANCE_SCOPED or ACCOUNT_SCOPED_WHOLLY_DROPPED in %s.',
                    $entityClass,
                    self::class,
                ),
            );
        }
    }

    public function testEveryBackedUpFieldReachesTheExportersOutput(): void
    {
        $valuesByKind = $this->exportedValuesByKind('coverage@example.com');

        foreach (self::BACKED_UP as $entityClass => $fields) {
            $kind = self::KIND_OF[$entityClass];
            foreach ($fields as $field => $declared) {
                foreach ($this->exportedKeysFor($declared) as $exportedKey) {
                    $this->assertBackedUpFieldReachedTheExport(
                        $entityClass,
                        $field,
                        $exportedKey,
                        $kind,
                        $valuesByKind,
                    );
                }
            }
        }
    }

    /**
     * A key present with a null value would satisfy a bare "was the key
     * written" check just as well as a real one, so the write-direction proof
     * has to look at the value, not merely the key — and `FullyPopulatedAccount`
     * exists precisely so every declared field has a real value to check
     * against here (#556).
     *
     * No field is excused from this today: every `BACKED_UP` field is a
     * scalar (or a list of them) that `FullyPopulatedAccount` can set to a
     * real value, so there is currently no case of a field that legitimately
     * has to stay null. If one is found, name it in a small, explicitly
     * commented exception here rather than weakening the assertion below for
     * every field.
     *
     * @param array<string, array<string, list<mixed>>> $valuesByKind
     */
    private function assertBackedUpFieldReachedTheExport(
        string $entityClass,
        string $field,
        string $exportedKey,
        string $kind,
        array $valuesByKind,
    ): void {
        self::assertArrayHasKey(
            $exportedKey,
            $valuesByKind[$kind] ?? [],
            sprintf(
                '%s::$%s is declared BACKED_UP as "%s" on the %s line, but the exporter '
                . 'never writes that key.',
                $entityClass,
                $field,
                $exportedKey,
                $kind,
            ),
        );

        foreach ($valuesByKind[$kind][$exportedKey] as $value) {
            self::assertNotNull(
                $value,
                sprintf(
                    '%s::$%s is declared BACKED_UP as "%s" on the %s line, but a fully '
                    . 'populated account still exports it as null. Populate the field in '
                    . 'FullyPopulatedAccount — that class exists to make this exact failure '
                    . 'impossible.',
                    $entityClass,
                    $field,
                    $exportedKey,
                    $kind,
                ),
            );
        }
    }

    /**
     * The other direction: nothing reaches the file that this class has not
     * accounted for.
     *
     * This is what keeps ACCOUNT_SCOPED_WHOLLY_DROPPED's per-entity shorthand
     * honest. Those six entities have no field-by-field declaration, so the
     * only way to notice one of them starting to be exported is to insist that
     * every key on every line is claimed by some declaration here.
     */
    public function testTheExportWritesNoKeyThatNoDeclarationClaims(): void
    {
        self::assertSame(
            [],
            $this->undeclaredExportedKeysByKind('dropped@example.com'),
            sprintf(
                "The exporter writes keys that no declaration in %s claims.\n"
                . 'If a wholly dropped entity has started reaching the file it is now partly '
                . 'backed up: move it to BACKED_UP and NOT_BACKED_UP, field by field. '
                . 'Otherwise declare the new key against the field it comes from.',
                self::class,
            ),
        );
    }

    /**
     * The reason strings above are for whoever hits a red test. This asserts
     * the user-facing table cannot silently fall behind them — the coupling is
     * mechanical, the wording stays hand-written.
     *
     * Scoped per section because a backticked name is not unique across the
     * page: unscoped, section 5's `createdAt` would answer for a User row that
     * 6.3 had lost. Two declarations of one name inside a single section still
     * alias each other — User's and Feed's `status` rows both sit in 6.3 — so
     * the floor this holds is one row per name per section.
     */
    public function testEveryDroppedThingAppearsInTheUserFacingDoc(): void
    {
        $doc = (string) file_get_contents(__DIR__ . '/../../../../docs/backup.md');

        $this->assertEveryEntityIsMentioned(self::INSTANCE_SCOPED, $doc, self::SECTION_INSTANCE_SCOPED);
        $this->assertEveryEntityIsMentioned(self::ACCOUNT_SCOPED_WHOLLY_DROPPED, $doc, self::SECTION_WHOLLY_DROPPED);

        $this->assertEveryFieldHasARow(self::NOT_BACKED_UP, $doc, self::SECTION_DROPPED_FIELDS);
        $this->assertEveryFieldHasARow(self::NEVER_BACKED_UP, $doc, self::SECTION_NEVER_WRITTEN);
    }

    /**
     * @param array<class-string, string> $declarations
     */
    private function assertEveryEntityIsMentioned(array $declarations, string $doc, string $sectionMarker): void
    {
        $section = $this->sectionOf($doc, $sectionMarker);

        foreach (array_keys($declarations) as $entityClass) {
            $shortName = (new \ReflectionClass($entityClass))->getShortName();
            self::assertStringContainsString(
                $shortName,
                $section,
                sprintf(
                    'docs/backup.md section "%s" never mentions %s, which a backup drops.',
                    $sectionMarker,
                    $shortName,
                ),
            );
        }
    }

    /**
     * @param array<class-string, array<string, string>> $declarations
     */
    private function assertEveryFieldHasARow(array $declarations, string $doc, string $sectionMarker): void
    {
        $section = $this->sectionOf($doc, $sectionMarker);

        foreach ($declarations as $entityClass => $fields) {
            foreach (array_keys($fields) as $field) {
                self::assertStringContainsString(
                    '`' . $field . '`',
                    $section,
                    sprintf(
                        'docs/backup.md section "%s" has no row for %s::$%s, which a backup drops.',
                        $sectionMarker,
                        $entityClass,
                        $field,
                    ),
                );
            }
        }
    }

    /**
     * The lines under one heading, down to the next heading of the same or a
     * higher level. Empty is not a passing state: a renumbered page has to
     * fail here, rather than let every search run against nothing and pass.
     */
    private function sectionOf(string $doc, string $marker): string
    {
        $level = \strlen(explode(' ', $marker, 2)[0]);
        $collected = [];
        $inside = false;

        foreach (explode("\n", $doc) as $line) {
            if (!$inside) {
                $inside = str_starts_with($line, $marker);
                continue;
            }
            if ($this->startsANewSection($line, $level)) {
                break;
            }
            $collected[] = $line;
        }

        self::assertNotSame([], $collected, sprintf('docs/backup.md has no section "%s".', $marker));

        return implode("\n", $collected);
    }

    private function startsANewSection(string $line, int $level): bool
    {
        $hashes = strspn($line, '#');

        return 0 < $hashes && $hashes <= $level;
    }

    /**
     * @param string|list<string> $declared
     *
     * @return list<string>
     */
    private function exportedKeysFor(string|array $declared): array
    {
        return \is_string($declared) ? [$declared] : $declared;
    }

    /**
     * @param class-string $entityClass
     *
     * @return list<string> field names, embeddable parts and associations
     */
    private function persistedNames(string $entityClass): array
    {
        $metadata = $this->em->getClassMetadata($entityClass);
        $names = array_merge($metadata->getFieldNames(), $metadata->getAssociationNames());

        return array_values(array_diff($names, self::UNIVERSALLY_SKIPPED));
    }

    private function isDeclared(string $entityClass, string $name): bool
    {
        foreach ([self::BACKED_UP, self::NOT_BACKED_UP, self::NEVER_BACKED_UP] as $declarations) {
            if (isset($declarations[$entityClass][$name])) {
                return true;
            }
        }

        return false;
    }

    private function hasScopeDecision(string $entityClass): bool
    {
        return isset(self::BACKED_UP[$entityClass])
            || isset(self::INSTANCE_SCOPED[$entityClass])
            || isset(self::ACCOUNT_SCOPED_WHOLLY_DROPPED[$entityClass]);
    }

    /** @return list<class-string> */
    private function mappedEntityClasses(): array
    {
        $classes = [];
        foreach ($this->em->getMetadataFactory()->getAllMetadata() as $metadata) {
            if ($metadata->isEmbeddedClass || $metadata->isMappedSuperclass) {
                continue;
            }
            $classes[] = $metadata->getName();
        }

        return $classes;
    }

    /**
     * Every key the export writes that no declaration in this class claims,
     * grouped by the kind of line it appeared on. Empty is the passing state.
     *
     * The accounting is per kind, not global. A global one would let any key
     * excuse itself against a declaration from a different line — `createdAt`
     * on the header would license a `createdAt` anywhere — and field names are
     * shared vocabulary across this schema, so a global set collapses to
     * nothing and the proof stops proving.
     *
     * @return array<string, list<string>>
     */
    private function undeclaredExportedKeysByKind(string $email): array
    {
        $undeclared = [];
        foreach ($this->exportedKeysByKind($email) as $kind => $keys) {
            $unclaimed = array_values(array_diff($keys, $this->claimedKeysOf($kind)));
            if ([] !== $unclaimed) {
                $undeclared[$kind] = $unclaimed;
            }
        }

        return $undeclared;
    }

    /** @return list<string> the keys one kind of line is allowed to carry */
    private function claimedKeysOf(string $kind): array
    {
        $keys = array_merge(self::EVERY_LINE, self::FILE_SCAFFOLDING[$kind] ?? []);
        foreach (self::BACKED_UP as $entityClass => $fields) {
            if (self::KIND_OF[$entityClass] !== $kind) {
                continue;
            }
            foreach ($fields as $declared) {
                $keys = array_merge($keys, $this->exportedKeysFor($declared));
            }
        }

        return $keys;
    }

    /**
     * Which JSON keys the exporter writes on each kind of line — the key half
     * of {@see exportedValuesByKind()}, derived from it rather than walking
     * the export a second time: the two questions ("which keys" and "which
     * values") share the exact same traversal, and a key list kept in step by
     * hand would be exactly the kind of drift this test suite exists to catch
     * elsewhere.
     *
     * @return array<string, list<string>>
     */
    private function exportedKeysByKind(string $email): array
    {
        return array_map(array_keys(...), $this->exportedValuesByKind($email));
    }

    /**
     * Seeds one fully populated account and reports, for each kind of line,
     * every value the exporter writes under each key — the same shape as
     * {@see exportedKeysByKind()}, but keeping the value rather than only
     * proving the key was present, because a null value would satisfy the
     * key-only proof just as well as a real one (#556).
     *
     * @return array<string, array<string, list<mixed>>>
     */
    private function exportedValuesByKind(string $email): array
    {
        $user = $this->fullyPopulatedAccount()->create($email);

        $valuesByKind = [];
        foreach ($this->exporter()->lines($user, 'https://coverage.example') as $line) {
            $decoded = json_decode($line, true, flags: \JSON_THROW_ON_ERROR);
            self::assertIsArray($decoded);
            /** @var array<string, mixed> $decoded */
            $kind = $decoded['kind'] ?? '';
            self::assertIsString($kind);
            foreach ($this->valuesOfOneLine($decoded) as $key => $values) {
                $valuesByKind[$kind][$key] = array_merge($valuesByKind[$kind][$key] ?? [], $values);
            }
        }

        return $valuesByKind;
    }

    /**
     * A line's own values, keyed by its own keys, plus a dotted key for each
     * key of a nested object — `recommendationSettings.profileText`,
     * `tags.position`. One level only: the format nests no deeper, and a
     * flattener that recursed would invent key names the exporter cannot
     * produce. A key maps to a list because a nested key repeats once per
     * element: two subscription tags both contribute a `tags.position` value.
     *
     * @param array<string, mixed> $line
     *
     * @return array<string, list<mixed>>
     */
    private function valuesOfOneLine(array $line): array
    {
        $values = [];
        foreach ($line as $key => $value) {
            $values[$key][] = $value;
            foreach ($this->nestedObjects($value) as $nested) {
                foreach ($nested as $nestedKey => $nestedValue) {
                    $values[$key . '.' . $nestedKey][] = $nestedValue;
                }
            }
        }

        return $values;
    }

    /**
     * The objects held under one key: the account line's recommendation
     * settings is a single object, a subscription line's tag references are a
     * list of several.
     *
     * @return list<array<array-key, mixed>>
     */
    private function nestedObjects(mixed $value): array
    {
        if (!is_array($value) || [] === $value) {
            return [];
        }

        if (!array_is_list($value)) {
            return [$value];
        }

        $objects = [];
        foreach ($value as $element) {
            if (is_array($element)) {
                $objects[] = $element;
            }
        }

        return $objects;
    }

    private function fullyPopulatedAccount(): FullyPopulatedAccount
    {
        $hasher = self::getContainer()->get(UserPasswordHasherInterface::class);
        self::assertInstanceOf(UserPasswordHasherInterface::class, $hasher);

        return new FullyPopulatedAccount($this->em, $hasher);
    }

    private function exporter(): AccountBackupExporter
    {
        $exporter = self::getContainer()->get(AccountBackupExporter::class);
        self::assertInstanceOf(AccountBackupExporter::class, $exporter);

        return $exporter;
    }
}
