<?php

declare(strict_types=1);

namespace App\Service\Reader;

use App\Service\Reader\Media\NarrationSignals;
use Dom\Element;
use Dom\HTMLDocument;

/**
 * Repairs what readability keeps of a page's script-driven player (#786). The
 * bare <audio>/<video> has no UI at all once its script is gone, so a player
 * that still names a file gets native controls; one whose file the sanitizer
 * stripped (ZEIT hides it in data-src, #903) is dropped instead, so no dead
 * control reaches the reader. The readouts that UI left behind — blocks whose
 * whole text is clock values, `0:00` beside `-13:34` — are removed together
 * with the wrapper they leave empty. A clock inside a sentence is prose and stays.
 *
 * The same pass drops a "copy this embed" widget (#922, NPR; generalised #959):
 * a label and a <code> block that show a player's <iframe> snippet as escaped,
 * literal text for a human to copy. Any host's embed matches — the tell is an
 * <iframe> tag with a src rendered as text, not a code sample a reader wrote —
 * and it is chrome, not content, so the reader shows source where an article
 * should be.
 *
 * It also drops a silent text-to-speech widget (#959): a container a page marks
 * as narration (`NarrationSignals`) but which holds no <audio> or <video> at
 * all, because the reading is generated by script on demand. Readability keeps
 * its icon and labels, and the reader has no player to attach — so a play glyph
 * and a disclaimer sit where the article should be. A narration container that
 * does hold a player is left for the player logic above to keep and mark.
 */
final readonly class PlayerChromeCleaner
{
    private const string CLOCK = '-?\d{1,2}:\d{2}(?::\d{2})?';

    private const string READOUT_PATTERN = '/^' . self::CLOCK . '(?:\s*[\/|]\s*' . self::CLOCK . ')*$/';

    private const array MEDIA_TAGS = ['img', 'audio', 'video', 'iframe', 'svg'];

    /** A code block whose literal text is an <iframe> embed snippet (src and
     *  all) is a "copy this embed" widget, not a code sample a reader wrote. */
    private const string EMBED_SNIPPET_PATTERN = '/<iframe\b[^>]*\bsrc=/i';

    public function cleanIn(HTMLDocument $document): void
    {
        $body = $document->body;
        if ($body === null) {
            return;
        }

        $this->restoreOrDropPlayers($document);
        foreach (LeadingEngagementBlocks::in($body) as $block) {
            if (preg_match(self::READOUT_PATTERN, $block->text) === 1) {
                $this->removeWithEmptiedWrappers($block->element, $body);
            }
        }
        foreach ($this->embedCodeBlocks($document) as $code) {
            $this->removeWithEmptiedWrappers($this->embedRow($code, $body) ?? $code, $body);
        }
        foreach ($this->silentNarrationWidgets($document) as $widget) {
            $this->removeWithEmptiedWrappers($widget, $body);
        }
    }

    /**
     * Narration containers with no player of their own, outermost first so a
     * nested tell is taken with the widget rather than left behind. Collected
     * before mutation so removals don't skip nodes.
     *
     * @return list<Element>
     */
    private function silentNarrationWidgets(HTMLDocument $document): array
    {
        $widgets = [];
        foreach ($document->querySelectorAll('*') as $element) {
            if (NarrationSignals::declaredOn($element) && !$this->holdsPlayer($element)) {
                $widgets[] = $element;
            }
        }

        return $widgets;
    }

    private function holdsPlayer(Element $element): bool
    {
        return $element->getElementsByTagName('audio')->length > 0
            || $element->getElementsByTagName('video')->length > 0;
    }

    /** @return list<Element> collected before mutation, so removals don't skip nodes */
    private function embedCodeBlocks(HTMLDocument $document): array
    {
        $blocks = [];
        foreach ($document->querySelectorAll('code') as $code) {
            if (preg_match(self::EMBED_SNIPPET_PATTERN, $code->textContent ?? '') === 1) {
                $blocks[] = $code;
            }
        }

        return $blocks;
    }

    /** The list row or paragraph around the code, so removing it takes the
     *  widget's "Embed" label with the <code> block instead of leaving it. */
    private function embedRow(Element $code, Element $body): ?Element
    {
        $node = $code->parentElement;
        while ($node !== null && $node !== $body) {
            if ($node->localName === 'li' || $node->localName === 'p') {
                return $node;
            }
            $node = $node->parentElement;
        }

        return null;
    }

    private function restoreOrDropPlayers(HTMLDocument $document): void
    {
        foreach ($document->querySelectorAll('audio, video') as $player) {
            if ($this->hasPlayableSource($player)) {
                if (!$player->hasAttribute('controls')) {
                    $player->setAttribute('controls', '');
                }
                continue;
            }
            // The sanitizer stripped the file (ZEIT hides it in data-src, #903);
            // a bare player would show controls that can never play.
            $player->remove();
        }
    }

    private function hasPlayableSource(Element $player): bool
    {
        $source = $player->getAttribute('src');

        return ($source !== null && $source !== '')
            || $player->getElementsByTagName('source')->length > 0;
    }

    private function removeWithEmptiedWrappers(Element $readout, Element $body): void
    {
        $wrapper = $readout->parentElement;
        $readout->remove();
        while ($wrapper !== null && $wrapper !== $body && $this->isEmptied($wrapper)) {
            $next = $wrapper->parentElement;
            $wrapper->remove();
            $wrapper = $next;
        }
    }

    private function isEmptied(Element $wrapper): bool
    {
        return LeadingEngagementRules::collapse($wrapper->textContent) === ''
            && !array_any(
                self::MEDIA_TAGS,
                static fn (string $tag): bool => $wrapper->getElementsByTagName($tag)->length > 0,
            );
    }
}
